apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpftrace-demo
  labels:
    app: bpftrace-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpftrace-demo
  template:
    metadata:
      labels:
        app: bpftrace-demo
    spec:
      containers:
      - name: demo
        image: alexb138/bpftrace-demo:latest
        command: ["./demo"]

